/**
 * The robot's pre-recorded voice (projector only): short MP3 lines generated by
 * scripts/voice.ts. Plays through the shared AudioContext, follows the mute
 * button, and ducks the music while it speaks.
 */
import type { VoiceLineId } from "../../shared/voice-lines.ts";
import { music } from "./music/index.ts";
import { getAudioContext, isMuted } from "./sounds.ts";
import binaryChant from "./voice/binary-chant.mp3";
import fleshIsWeak from "./voice/flesh-is-weak.mp3";
import onlyMetalEndures from "./voice/only-metal-endures.mp3";
import targetsAcquired from "./voice/targets-acquired.mp3";

const CLIPS: Record<VoiceLineId, string> = {
  "targets-acquired": targetsAcquired,
  "flesh-is-weak": fleshIsWeak,
  "only-metal-endures": onlyMetalEndures,
  "binary-chant": binaryChant,
};

const ON_KEY = "quizzer.voice";
const VOLUME = 1.1;

let enabled = (() => {
  try {
    return localStorage.getItem(ON_KEY) !== "0";
  } catch {
    return true;
  }
})();

export const voiceEnabled = () => enabled;

export function setVoiceEnabled(on: boolean): void {
  enabled = on;
  try {
    localStorage.setItem(ON_KEY, on ? "1" : "0");
  } catch {
    // storage unavailable: the setting just won't persist
  }
}

// Downloaded up front so a line plays the moment it's needed; decoded on first use.
const data = new Map<VoiceLineId, Promise<ArrayBuffer | null>>();
const decoded = new Map<VoiceLineId, AudioBuffer>();
/** When the line already playing (or queued) finishes, on the AudioContext clock. */
let busyUntil = 0;

function load(id: VoiceLineId): Promise<ArrayBuffer | null> {
  let p = data.get(id);
  if (!p) {
    p = fetch(CLIPS[id])
      .then((r) => (r.ok ? r.arrayBuffer() : null))
      .catch(() => null);
    data.set(id, p);
  }
  return p;
}

/** Start downloading lines a screen is going to need. */
export function preloadVoice(ids: VoiceLineId[]): void {
  for (const id of ids) void load(id);
}

/** Say a line, unless the voice is off or sounds are muted. Lines never overlap: a new one waits for the current one. */
export async function say(id: VoiceLineId): Promise<void> {
  const ctx = getAudioContext();
  if (!enabled || isMuted() || !ctx || ctx.state !== "running") return;
  let buf = decoded.get(id);
  if (!buf) {
    const raw = await load(id);
    if (!raw) return;
    try {
      // decodeAudioData detaches its input, so decode a copy and keep the download reusable.
      buf = await ctx.decodeAudioData(raw.slice(0));
    } catch {
      return;
    }
    decoded.set(id, buf);
  }
  const src = ctx.createBufferSource();
  const gain = ctx.createGain();
  src.buffer = buf;
  gain.gain.value = VOLUME;
  src.connect(gain).connect(ctx.destination);
  const at = Math.max(ctx.currentTime, busyUntil);
  busyUntil = at + buf.duration + 0.15;
  src.start(at);
  music.duck((busyUntil - ctx.currentTime) * 1000);
}
